package charger

// Code generated by github.com/andig/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/andig/evcc/api"
)

func decorateGoEEth(base *GoEEth, meter func() (float64, error), meterEnergy func() (float64, error), meterCurrent func() (float64, float64, float64, error)) api.Charger {
	switch {
	case meter == nil && meterCurrent == nil && meterEnergy == nil:
		return base

	case meter != nil && meterCurrent == nil && meterEnergy == nil:
		return &struct {
			*GoEEth
			api.Meter
		}{
			GoEEth: base,
			Meter: &decorateGoEEthMeterImpl{
				meter: meter,
			},
		}

	case meter == nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*GoEEth
			api.MeterEnergy
		}{
			GoEEth: base,
			MeterEnergy: &decorateGoEEthMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case meter != nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*GoEEth
			api.Meter
			api.MeterEnergy
		}{
			GoEEth: base,
			Meter: &decorateGoEEthMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateGoEEthMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case meter == nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*GoEEth
			api.MeterCurrent
		}{
			GoEEth: base,
			MeterCurrent: &decorateGoEEthMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case meter != nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*GoEEth
			api.Meter
			api.MeterCurrent
		}{
			GoEEth: base,
			Meter: &decorateGoEEthMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decorateGoEEthMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case meter == nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*GoEEth
			api.MeterCurrent
			api.MeterEnergy
		}{
			GoEEth: base,
			MeterCurrent: &decorateGoEEthMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateGoEEthMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case meter != nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*GoEEth
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
		}{
			GoEEth: base,
			Meter: &decorateGoEEthMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decorateGoEEthMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateGoEEthMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}
	}

	return nil
}

type decorateGoEEthMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateGoEEthMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateGoEEthMeterCurrentImpl struct {
	meterCurrent func() (float64, float64, float64, error)
}

func (impl *decorateGoEEthMeterCurrentImpl) Currents() (float64, float64, float64, error) {
	return impl.meterCurrent()
}

type decorateGoEEthMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateGoEEthMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}
